### ISSUE TITLE
Idea: prioritize certain colors

### ISSUE THREAD

**Issue by morrowwm** [ca-place/ca-place-script#4]
We're attempting to defend the old flag by fixing grey leaf outline pixels first. The loop which starts with

```
for (const j of order) {
        for (var l = 0; l < 10; l++) {
            const i = (j * 10) + l;
            // negeer lege order pixels.
            if (rgbaOrder[(i * 4) + 3] === 0) continue;

            const hex = rgbToHex(rgbaOrder[(i * 4)], rgbaOrder[(i * 4) + 1], rgbaOrder[(i * 4) + 2]);
```
be wrapped in a colour priority loop. Do special colours first, then colours that predominate in the image. Finally everything else.

**Comment by morrowwm** [comment]
Actually, better done with different image templates, as is currently feasible?

**Comment by Shrinks99** [comment]
Yeah, best to just do this by replacing the Imgur link with a different image.  I've left the template for the old flag in the `old-templates` folder, you'll need to resize the canvas to accommodate the new size but it should otherwise work.

**Comment by Shrinks99** [comment]
This has been done to target the flag only.
